package digital.capsa.archetypes.core

import java.util.UUID

const val PASSWORD_MIN_LENGTH = 4

const val PASSWORD_MAX_LENGTH = 100

const val EMAIL_MIN_LENGTH = 5

const val EMAIL_MAX_LENGTH = 254

const val COMPANY_NAME_MAX_LENGTH = 50

const val FIRST_NAME_MAX_LENGTH = 50

const val LAST_NAME_MAX_LENGTH = 50

const val AGENCY_NAME_MAX_LENGTH = 120

const val BRANCH_NAME_MAX_LENGTH = 120

const val PHONE_REGEX = "^\\+[0-9]{1,3}\\.[0-9]{4,14}(?:x.+)?$"

const val RANDOM_PASSWORD_LENGTH = 20

const val RANDOM_ACTIVATION_CODE_LENGTH = 20

const val RANDOM_RESET_KEY_LENGTH = 20

const val RANDOM_VALIDATION_CODE_LENGTH = 5

const val VALIDATION_DELAY_SEC = 10L

const val VALIDATION_TIMEOUT_SEC = 600L

const val CUSTOMER_NOTES_MAX_LENGTH = 3000

const val CONTACT_NOTES_MAX_LENGTH = 3000

const val LEAD_NOTES_MAX_LENGTH = 3000

const val MISSION_DESCRIPTION_MAX_LENGTH = 3000

const val TIME_LOG_DETAILS = 3000

const val TIMESHEET_DESCRIPTION = 3000

const val WORK_ITEM_DESCRIPTION = 3000

