spring:
  cloud:
    stream:
      bindings:
        event-bus-input:
          destination: capsa-event-bus-local
          binder: kafka
          group: integrationTest
      schema-registry-client:
        endpoint: http://localhost:8081
capsa:
  host: localhost
  port: 8080
  schema: http
