spring:
  cloud:
    stream:
      bindings:
        event-bus-input:
          destination: capsa-event-bus-local
          binder: kafka
          group: integrationTest
      schema-registry-client:
        endpoint: http://localhost:8081
capsa:
  command:
    host: localhost
    port: 9590
  query:
    host: localhost
    port: 9591
  schema: http
