spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      binders:
        kafka:
          type: kafka
      kafka:
        binder:
          headers: eventType
        bindings:
          event-bus-input:
            consumer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.StringSerializer
      inMemory:
        binder:
          headers: eventType
context:
  initializer:
    classes: digital.capsa.archetypes.tests.ContextInitializer