spring:
  cloud:
    stream:
      kafka:
        bindings:
          event-bus-output:
            destination: capsa-event-bus-local
            producer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.StringSerializer
      bindings:
        event-bus-output:
          destination: capsa-event-bus-local
          binder: kafka
          group: capsaApp
      schema-registry-client:
        endpoint: http://localhost:8081
server:
  port: 9590
info:
  app:
    env: local
