spring:
  cloud:
    stream:
      kafka:
        bindings:
          event-bus-output:
            destination: capsa-event-bus-local
            producer:
              configuration:
                key:
                  serializer: org.apache.kafka.common.serialization.StringSerializer
      bindings:
        event-bus-output:
          destination: capsa-event-bus-local
          binder: kafka
          group: capsaApp
      schema-registry-client:
        endpoint: http://localhost:8081
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    properties:
    ###### generate schema ########
    #      javax:
    #        persistence:
    #          schema-generation:
    #            create-source: metadata
    #            scripts:
    #              action: create
    #              create-target: metrofox-monolith/build/db/create.sql
    hibernate:
      ddl-auto: create
server:
  port: 8080
info:
  app:
    env: local
