spring:
  cloud:
    stream:
      bindings:
        event-bus-input:
          destination: capsa-event-bus-local
          binder: kafka
          group: capsaApp
      schema-registry-client:
        endpoint: http://localhost:8081
server:
  port: 9591
info:
  app:
    env: local
