spring:
  cloud:
    stream:
      bindings:
        event-bus-output:
          destination: metrofox-event-bus-local
          binder: kafka
        event-bus-input:
          destination: metrofox-event-bus-local
          binder: kafka
      schema-registry-client:
        endpoint: http://localhost:8081
server:
  port: 9591
info:
  app:
    env: local
metrofox:
  apiGateway:
    uri: http://localhost:8080
  app:
    uri: http://localhost