spring:
  kafka:
    bootstrap-servers:
      - pkc-4yyd6.us-east1.gcp.confluent.cloud:9092
    properties:
      # CCloud broker connection parameters
      ssl.endpoint.identification.algorithm: https
      sasl.mechanism: PLAIN
      request.timeout.ms: 20000
      retry.backoff.ms: 500
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="QVA55CKWYUP27PWE" password="g73Hdd2yvqVO10YKdEFzjLF19Td1xNk2K5nsuxO3JmLQHhBuSarL8l4HLYis8yko";
      security.protocol: SASL_SSL

      # CCloud Schema Registry Connection parameter
      schema.registry.url: https://psrc-lz3xz.us-central1.gcp.confluent.cloud
      basic.auth.credentials.source: USER_INFO
      schema.registry.basic.auth.user.info: YPXENZTACHSLHLKX:YSIq8qGH20yIcAb1mHDnTzh5/PgXRs/IfXOzpgRAjGaYHrnIolO+ThgNsfX3JPk/
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    template:
      default-topic:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            configuration:
              replication:
                factor: 3
        binder:
          replication-factor: 3
      bindings:
        event-bus-input:
          destination: capsa-event-bus-dev
          binder: kafka
      schema-registry-client:
        endpoint: https://psrc-lz3xz.us-central1.gcp.confluent.cloud
info:
  app:
    env: dev
