dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("io.ktor:ktor-server-netty")
    implementation("io.ktor:ktor-jackson")
    implementation("io.ktor:ktor")
    implementation("org.jetbrains.exposed:exposed")
    implementation("org.jetbrains.kotlin:kotlin-noarg")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.postgresql:postgresql")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.cloud:spring-cloud-starter-stream-kafka")
    implementation(project(":capsa-archetypes-core"))
    implementation(project(":capsa-archetypes-eventbus"))
    testImplementation("org.springframework.boot:spring-boot-starter-test")
}
