spring:
  cloud:
    stream:
      bindings:
        event-bus-output:
          destination: capsa-event-bus-local
          binder: kafka
        event-bus-input:
          destination: capsa-event-bus-local
          binder: kafka
      schema-registry-client:
        endpoint: http://localhost:8081
server:
  port: 9590
info:
  app:
    env: local
