spring:
  datasource:
    url: jdbc:postgresql://metrofox-do-user-2192421-0.db.ondigitalocean.com:25060/metrofox-dev?sslmode=require
    username: metrofox-admin
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
  jpa:
    hibernate:
      ddl-auto: create
  kafka:
    bootstrap-servers:
      - pkc-43n10.us-central1.gcp.confluent.cloud:9092
    properties:
      # CCloud broker connection parameters
      ssl.endpoint.identification.algorithm: https
      sasl.mechanism: PLAIN
      request.timeout.ms: 20000
      retry.backoff.ms: 500
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="AW3LELBZCR6ASAGR" password="dL716uS8fukzJ0Dam2u/934okavvLSE7O3/MBgBAdyhj1+eGUVaUI5sOTZLmQ4z8";
      security.protocol: SASL_SSL

      # CCloud Schema Registry Connection parameter
      schema.registry.url: https://psrc-lz3xz.us-central1.gcp.confluent.cloud
      basic.auth.credentials.source: USER_INFO
      schema.registry.basic.auth.user.info: YPXENZTACHSLHLKX:YSIq8qGH20yIcAb1mHDnTzh5/PgXRs/IfXOzpgRAjGaYHrnIolO+ThgNsfX3JPk/
    consumer:
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    template:
      default-topic:
  cloud:
    stream:
      kafka:
        streams:
          binder:
            configuration:
              replication:
                factor: 3
        binder:
          replication-factor: 3
      bindings:
        event-bus-output:
          destination: metrofox-event-bus-dev
          binder: kafka
        event-bus-input:
          destination: metrofox-event-bus-dev
          binder: kafka
        aggregate-output:
          destination: metrofox-aggregates-dev
          binder: inMemory
        aggregate-input:
          destination: metrofox-aggregates-dev
          binder: inMemory
      schema-registry-client:
        endpoint: https://psrc-lz3xz.us-central1.gcp.confluent.cloud
  mail:
    host: test-doubles.metrofoxsecurity.com
    port: 3025
    noreply:
      user: noreply@metrofoxsecurity.com
      password: Password1
    info:
      user: info@metrofoxsecurity.com
      password: Password1
info:
  app:
    env: dev
metrofox:
  apiGateway:
    uri: http://127.0.0.1:8080
  app:
    uri: http://app-dev.metrofoxsecurity.com