spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  main:
    allow-bean-definition-overriding: true
  cloud:
    stream:
      binders:
        kafka:
          type: kafka
      kafka:
        binder:
          headers: eventType
      inMemory:
        binder:
          headers: eventType
server:
  servlet:
    context-path: /api
info:
  app:
    name:  Capsa Command Application
    version: 0.0.2
