Feature: Staffer CRUD

  Scenario Outline: Call getStafferDetails - <description>
    When sending http request from file /requests/authorize.json using the following transformations:
      | path            | value     |
      | $.schema        | http      |
      | $.host          | <host>    |
      | $.body.username | admin@en  |
      | $.body.password | Password1 |
    And verifying status code is 200
    And saving response parts to context memento
      | path    | variable |
      | $.token | jwtToken |
    And sending http request from file /requests/inflate-account-topology.json using the following transformations:
      | path     | value  |
      | $.schema | http   |
      | $.host   | <host> |
    And verifying status code is 200
    And sending http request from file /requests/staffer-list.json using the following transformations:
      | path                        | value        |
      | $.schema                    | http         |
      | $.host                      | <host>       |
      | $.body.agencyId             | [[agencyId]] |
      | $.body.pageNumber           | {1}          |
      | $.body.pageSize             | {15}         |
      | $.body.search               |              |
      | $.body.accreditationSet     | {null}       |
      | $.body.stafferType          | employee     |
      | $.body.statusTypes          | {null}       |
      | $.body.firstSortBy          | firstName   |
      | $.body.firstSortDescending  | {false}      |
      | $.body.secondSortBy         | lastName    |
      | $.body.secondSortDescending | {false}      |
    And verifying status code is 200
    And saving response parts to context memento
      | path                       | variable  |
      | $.stafferList[0].stafferId | stafferId |

    And verifying status code is 200
    Then sending http request from file /requests/staffer-details.json using the following transformations:
      | path     | value                                |
      | $.schema | http                                 |
      | $.host   | <host>                               |
      | $.path   | /api/getStafferDetails/[[stafferId]] |
    And verifying status code is 200
    And verifying response body paths
      | path                         | value                                                                                                 |
      | $.firstName                  | Andrew                                                                                                |
      | $.lastName                   | Mcbride                                                                                               |
      | $.email                      | Andrew.Mcbride@en38                                                                                   |
      | $.status                     | OutSick                                                                                               |
      | $.stafferType                | employee                                                                                              |
      | $.accreditationList.length() | {7}                                                                                                   |
      | $.accreditationList[*].type  | armedGuard, palpation, residentialGuard, restrainingDevice, privateInvestigator, businessGuard, baton |

    @local
    Examples:
      | description       | host      |
      | positive scenario | localhost |

    @dev
    Examples:
      | description       | host                         |
      | positive scenario | api-dev.metrofoxsecurity.com |


  Scenario Outline: Call getStafferList with default filters/sort - <description>
    When sending http request from file /requests/authorize.json using the following transformations:
      | path            | value     |
      | $.schema        | http      |
      | $.host          | <host>    |
      | $.body.username | admin@en  |
      | $.body.password | Password1 |
    And verifying status code is 200
    And saving response parts to context memento
      | path    | variable |
      | $.token | jwtToken |
    And sending http request from file /requests/inflate-account-topology.json using the following transformations:
      | path     | value  |
      | $.schema | http   |
      | $.host   | <host> |
    And verifying status code is 200
    And sending http request from file /requests/staffer-list.json using the following transformations:
      | path                        | value        |
      | $.schema                    | http         |
      | $.host                      | <host>       |
      | $.body.agencyId             | [[agencyId]] |
      | $.body.pageNumber           | {1}          |
      | $.body.pageSize             | {15}         |
      | $.body.search               |              |
      | $.body.accreditationSet     | {null}       |
      | $.body.stafferType          | {null}       |
      | $.body.statusTypes          | {null}       |
      | $.body.firstSortBy          | firstName   |
      | $.body.firstSortDescending  | {false}      |
      | $.body.secondSortBy         | lastName    |
      | $.body.secondSortDescending | {false}      |
    Then verifying status code is 200

    And verifying response body paths
      | path                               | value                                                                                                         |
      | $.stafferList[*].firstName         | Alannah, Aminah, Andrew, Angie, Annabelle, Charlotte                                                          |
      | $.stafferList[*].lastName          | Walton, Holmes, Hubbard, Snyder, Berry, Fleming, Mcbride, Rivera, Todd, Perez, Elliott, Mccarthy              |
      | $.stafferList[0].firstName         | Alannah                                                                                                       |
      | $.stafferList[0].lastName          | Walton                                                                                                        |
      | $.stafferList[0].email             | Alannah.Walton@en44                                                                                           |
      | $.stafferList[0].phone             | +1 432 345-6789                                                                                               |
      | $.stafferList[0].status            | OnBreak                                                                                                       |
      | $.stafferList[0].stafferType       | contract                                                                                                      |
      | $.stafferList[0].accreditationList | armedGuard, palpation, residentialGuard, plainclothes, ownCar                                                 |
      | $.stafferList[2].firstName         | Aminah                                                                                                        |
      | $.stafferList[2].lastName          | Hubbard                                                                                                       |
      | $.stafferList[2].email             | Aminah.Hubbard@en7                                                                                            |
      | $.stafferList[2].phone             | +1 432 345-6789                                                                                               |
      | $.stafferList[2].status            | Available                                                                                                     |
      | $.stafferList[2].stafferType       | contract                                                                                                      |
      | $.stafferList[2].accreditationList | businessGuard, armedGuard, driverLicense, palpation, guardDogHandler, restrainingDevice, plainclothes, ownCar |

    @local
    Examples:
      | description         | host      |
      | positive scenario 1 | localhost |

    @dev
    Examples:
      | description         | endpoint                                 | host                         |
      | positive scenario 1 | http://api-dev.metrofoxsecurity.com:8080 | api-dev.metrofoxsecurity.com |


  Scenario Outline: Call getStafferList with variety of filters - <description>
    When sending http request from file /requests/authorize.json using the following transformations:
      | path            | value     |
      | $.schema        | http      |
      | $.host          | <host>    |
      | $.body.username | admin@en  |
      | $.body.password | Password1 |
    And verifying status code is 200
    And saving response parts to context memento
      | path    | variable |
      | $.token | jwtToken |
    And sending http request from file /requests/inflate-account-topology.json using the following transformations:
      | path     | value  |
      | $.schema | http   |
      | $.host   | <host> |
    And verifying status code is 200
    And sending http request from file /requests/staffer-list.json using the following transformations:
      | path                        | value                |
      | $.schema                    | http                 |
      | $.host                      | <host>               |
      | $.body.agencyId             | [[agencyId]]         |
      | $.body.pageNumber           | {1}                  |
      | $.body.pageSize             | {100}                |
      | $.body.search               | {<search>}           |
      | $.body.accreditationSet     | {<accreditationSet>} |
      | $.body.stafferType          | {<stafferType>}      |
      | $.body.statusTypes          | {<statusTypes>}      |
      | $.body.firstSortBy          | firstName           |
      | $.body.firstSortDescending  | {false}              |
      | $.body.secondSortBy         | lastName            |
      | $.body.secondSortDescending | {false}              |
    Then verifying status code is 200
    And verifying response body paths
      | path                   | value    |
      | $.stafferList[*].email | <emails> |

    @local
    Examples:
      | description                                             | host      | search    | accreditationSet                            | stafferType | statusTypes | emails                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
      | search:""                                               | localhost | ""        | null                                        | null        | null        | Alannah.Walton@en44, Aminah.Holmes@en15, Aminah.Hubbard@en7, Aminah.Snyder@en27, Andrew.Berry@en9, Andrew.Fleming@en49, Andrew.Mcbride@en38, Andrew.Rivera@en48, Andrew.Snyder@en3, Andrew.Todd@en23, Angie.Perez@en29, Annabelle.Elliott@en11, Annabelle.Snyder@en31, Charlotte.Mccarthy@en6, Charlotte.Rivera@en42, Daniel.Edwards@en18, Daniel.Hunt@en36, Daniel.O'Brien@en45, Daniel.Perez@en24, Ellie-Mae.Johnston@en39, Florence.Fleming@en10, Florence.Hubbard@en8, Florence.Mccarthy@en30, Genevieve.Rivera@en12, James.Hubbard@en13, James.Johnston@en40, Jason.Crawford@en47, Jason.Hunt@en20, Jason.Walton@en28, Jesse.Berry@en43, John.Berry@en22, Joshua.Edwards@en34, Katy.Crawford@en16, Katy.Johnston@en21, Matthew.Elliott@en5, Matthew.Hunt@en46, Matthew.Mcbride@en0, admin@en, Nella.Snyder@en14, Patrick.Kelley@en32, Patrick.O'Brien@en41, Robert.Abbott@en37, Robert.Holmes@en33, Ryan.Fleming@en35, Ryan.Holmes@en1, Ryan.Johnston@en4, Ryan.O'Brien@en25, Ryan.Walton@en17, William.Burke@en26, William.Holmes@en19, William.Hunt@en2 |
      | search:"  "                                             | localhost | "  "      | null                                        | null        | null        | Alannah.Walton@en44, Aminah.Holmes@en15, Aminah.Hubbard@en7, Aminah.Snyder@en27, Andrew.Berry@en9, Andrew.Fleming@en49, Andrew.Mcbride@en38, Andrew.Rivera@en48, Andrew.Snyder@en3, Andrew.Todd@en23, Angie.Perez@en29, Annabelle.Elliott@en11, Annabelle.Snyder@en31, Charlotte.Mccarthy@en6, Charlotte.Rivera@en42, Daniel.Edwards@en18, Daniel.Hunt@en36, Daniel.O'Brien@en45, Daniel.Perez@en24, Ellie-Mae.Johnston@en39, Florence.Fleming@en10, Florence.Hubbard@en8, Florence.Mccarthy@en30, Genevieve.Rivera@en12, James.Hubbard@en13, James.Johnston@en40, Jason.Crawford@en47, Jason.Hunt@en20, Jason.Walton@en28, Jesse.Berry@en43, John.Berry@en22, Joshua.Edwards@en34, Katy.Crawford@en16, Katy.Johnston@en21, Matthew.Elliott@en5, Matthew.Hunt@en46, Matthew.Mcbride@en0, admin@en, Nella.Snyder@en14, Patrick.Kelley@en32, Patrick.O'Brien@en41, Robert.Abbott@en37, Robert.Holmes@en33, Ryan.Fleming@en35, Ryan.Holmes@en1, Ryan.Johnston@en4, Ryan.O'Brien@en25, Ryan.Walton@en17, William.Burke@en26, William.Holmes@en19, William.Hunt@en2 |
      | search:null                                             | localhost | null      | null                                        | null        | null        | Alannah.Walton@en44, Aminah.Holmes@en15, Aminah.Hubbard@en7, Aminah.Snyder@en27, Andrew.Berry@en9, Andrew.Fleming@en49, Andrew.Mcbride@en38, Andrew.Rivera@en48, Andrew.Snyder@en3, Andrew.Todd@en23, Angie.Perez@en29, Annabelle.Elliott@en11, Annabelle.Snyder@en31, Charlotte.Mccarthy@en6, Charlotte.Rivera@en42, Daniel.Edwards@en18, Daniel.Hunt@en36, Daniel.O'Brien@en45, Daniel.Perez@en24, Ellie-Mae.Johnston@en39, Florence.Fleming@en10, Florence.Hubbard@en8, Florence.Mccarthy@en30, Genevieve.Rivera@en12, James.Hubbard@en13, James.Johnston@en40, Jason.Crawford@en47, Jason.Hunt@en20, Jason.Walton@en28, Jesse.Berry@en43, John.Berry@en22, Joshua.Edwards@en34, Katy.Crawford@en16, Katy.Johnston@en21, Matthew.Elliott@en5, Matthew.Hunt@en46, Matthew.Mcbride@en0, admin@en, Nella.Snyder@en14, Patrick.Kelley@en32, Patrick.O'Brien@en41, Robert.Abbott@en37, Robert.Holmes@en33, Ryan.Fleming@en35, Ryan.Holmes@en1, Ryan.Johnston@en4, Ryan.O'Brien@en25, Ryan.Walton@en17, William.Burke@en26, William.Holmes@en19, William.Hunt@en2 |
      | search:"John"                                           | localhost | "John"    | null                                        | null        | null        | Ellie-Mae.Johnston@en39, James.Johnston@en40, John.Berry@en22, Katy.Johnston@en21, Ryan.Johnston@en4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | search:"John"                                           | localhost | "John "   | null                                        | null        | null        | Ellie-Mae.Johnston@en39, James.Johnston@en40, John.Berry@en22, Katy.Johnston@en21, Ryan.Johnston@en4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | search:"john"                                           | localhost | " joHn"   | listOf<String>()                            | null        | null        | Ellie-Mae.Johnston@en39, James.Johnston@en40, John.Berry@en22, Katy.Johnston@en21, Ryan.Johnston@en4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | search:"n23"                                            | localhost | "n23"     | null                                        | null        | null        | Andrew.Todd@en23                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | search:"Robert."                                        | localhost | "Robert." | null                                        | null        | null        | Robert.Abbott@en37, Robert.Holmes@en33                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
      | accreditationSet:["privateInvestigator"]                | localhost | ""        | listOf("privateInvestigator")               | null        | null        | Andrew.Fleming@en49, Andrew.Mcbride@en38, Andrew.Snyder@en3, Andrew.Todd@en23, Angie.Perez@en29, Annabelle.Elliott@en11, Annabelle.Snyder@en31, Charlotte.Mccarthy@en6, Charlotte.Rivera@en42, Daniel.Edwards@en18, Florence.Mccarthy@en30, James.Hubbard@en13, James.Johnston@en40, Jason.Hunt@en20, Jason.Walton@en28, Katy.Johnston@en21, Matthew.Elliott@en5, Matthew.Hunt@en46, Patrick.O'Brien@en41, Robert.Abbott@en37, Ryan.Johnston@en4, Ryan.O'Brien@en25, Ryan.Walton@en17, William.Holmes@en19, William.Hunt@en2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
      | accreditationSet:["privateInvestigator", "armedGuard"]  | localhost | ""        | listOf("privateInvestigator", "armedGuard") | null        | null        | Andrew.Fleming@en49, Andrew.Mcbride@en38, Andrew.Snyder@en3, Angie.Perez@en29, Charlotte.Rivera@en42, James.Johnston@en40, Jason.Walton@en28, Matthew.Hunt@en46, Robert.Abbott@en37, Ryan.Johnston@en4, Ryan.O'Brien@en25, William.Holmes@en19, William.Hunt@en2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | search:"John", accreditationSet:["privateInvestigator"] | localhost | "John"    | listOf("privateInvestigator")               | null        | null        | James.Johnston@en40, Katy.Johnston@en21, Ryan.Johnston@en4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
      | all                                                     | localhost | "John"    | listOf("privateInvestigator")               | "employee"  | "Vacation"  | Katy.Johnston@en21                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |

    @dev
    Examples:
      | description                                             | host                         | search    | accreditationSet                            | stafferType | statusTypes | emails                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
      | search:""                                               | api-dev.metrofoxsecurity.com | ""        | null                                        | null        | null        | Alannah.Walton@en44, Aminah.Holmes@en15, Aminah.Hubbard@en7, Aminah.Snyder@en27, Andrew.Berry@en9, Andrew.Fleming@en49, Andrew.Mcbride@en38, Andrew.Rivera@en48, Andrew.Snyder@en3, Andrew.Todd@en23, Angie.Perez@en29, Annabelle.Elliott@en11, Annabelle.Snyder@en31, Charlotte.Mccarthy@en6, Charlotte.Rivera@en42, Daniel.Edwards@en18, Daniel.Hunt@en36, Daniel.O'Brien@en45, Daniel.Perez@en24, Ellie-Mae.Johnston@en39, Florence.Fleming@en10, Florence.Hubbard@en8, Florence.Mccarthy@en30, Genevieve.Rivera@en12, James.Hubbard@en13, James.Johnston@en40, Jason.Crawford@en47, Jason.Hunt@en20, Jason.Walton@en28, Jesse.Berry@en43, John.Berry@en22, Joshua.Edwards@en34, Katy.Crawford@en16, Katy.Johnston@en21, Matthew.Elliott@en5, Matthew.Hunt@en46, Matthew.Mcbride@en0, admin@en, Nella.Snyder@en14, Patrick.Kelley@en32, Patrick.O'Brien@en41, Robert.Abbott@en37, Robert.Holmes@en33, Ryan.Fleming@en35, Ryan.Holmes@en1, Ryan.Johnston@en4, Ryan.O'Brien@en25, Ryan.Walton@en17, William.Burke@en26, William.Holmes@en19, William.Hunt@en2 |
      | search:"  "                                             | api-dev.metrofoxsecurity.com | "  "      | null                                        | null        | null        | Alannah.Walton@en44, Aminah.Holmes@en15, Aminah.Hubbard@en7, Aminah.Snyder@en27, Andrew.Berry@en9, Andrew.Fleming@en49, Andrew.Mcbride@en38, Andrew.Rivera@en48, Andrew.Snyder@en3, Andrew.Todd@en23, Angie.Perez@en29, Annabelle.Elliott@en11, Annabelle.Snyder@en31, Charlotte.Mccarthy@en6, Charlotte.Rivera@en42, Daniel.Edwards@en18, Daniel.Hunt@en36, Daniel.O'Brien@en45, Daniel.Perez@en24, Ellie-Mae.Johnston@en39, Florence.Fleming@en10, Florence.Hubbard@en8, Florence.Mccarthy@en30, Genevieve.Rivera@en12, James.Hubbard@en13, James.Johnston@en40, Jason.Crawford@en47, Jason.Hunt@en20, Jason.Walton@en28, Jesse.Berry@en43, John.Berry@en22, Joshua.Edwards@en34, Katy.Crawford@en16, Katy.Johnston@en21, Matthew.Elliott@en5, Matthew.Hunt@en46, Matthew.Mcbride@en0, admin@en, Nella.Snyder@en14, Patrick.Kelley@en32, Patrick.O'Brien@en41, Robert.Abbott@en37, Robert.Holmes@en33, Ryan.Fleming@en35, Ryan.Holmes@en1, Ryan.Johnston@en4, Ryan.O'Brien@en25, Ryan.Walton@en17, William.Burke@en26, William.Holmes@en19, William.Hunt@en2 |
      | search:null                                             | api-dev.metrofoxsecurity.com | null      | null                                        | null        | null        | Alannah.Walton@en44, Aminah.Holmes@en15, Aminah.Hubbard@en7, Aminah.Snyder@en27, Andrew.Berry@en9, Andrew.Fleming@en49, Andrew.Mcbride@en38, Andrew.Rivera@en48, Andrew.Snyder@en3, Andrew.Todd@en23, Angie.Perez@en29, Annabelle.Elliott@en11, Annabelle.Snyder@en31, Charlotte.Mccarthy@en6, Charlotte.Rivera@en42, Daniel.Edwards@en18, Daniel.Hunt@en36, Daniel.O'Brien@en45, Daniel.Perez@en24, Ellie-Mae.Johnston@en39, Florence.Fleming@en10, Florence.Hubbard@en8, Florence.Mccarthy@en30, Genevieve.Rivera@en12, James.Hubbard@en13, James.Johnston@en40, Jason.Crawford@en47, Jason.Hunt@en20, Jason.Walton@en28, Jesse.Berry@en43, John.Berry@en22, Joshua.Edwards@en34, Katy.Crawford@en16, Katy.Johnston@en21, Matthew.Elliott@en5, Matthew.Hunt@en46, Matthew.Mcbride@en0, admin@en, Nella.Snyder@en14, Patrick.Kelley@en32, Patrick.O'Brien@en41, Robert.Abbott@en37, Robert.Holmes@en33, Ryan.Fleming@en35, Ryan.Holmes@en1, Ryan.Johnston@en4, Ryan.O'Brien@en25, Ryan.Walton@en17, William.Burke@en26, William.Holmes@en19, William.Hunt@en2 |
      | search:"John"                                           | api-dev.metrofoxsecurity.com | "John"    | null                                        | null        | null        | Ellie-Mae.Johnston@en39, James.Johnston@en40, John.Berry@en22, Katy.Johnston@en21, Ryan.Johnston@en4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | search:"John"                                           | api-dev.metrofoxsecurity.com | "John "   | null                                        | null        | null        | Ellie-Mae.Johnston@en39, James.Johnston@en40, John.Berry@en22, Katy.Johnston@en21, Ryan.Johnston@en4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | search:"john"                                           | api-dev.metrofoxsecurity.com | " joHn"   | listOf<String>()                            | null        | null        | Ellie-Mae.Johnston@en39, James.Johnston@en40, John.Berry@en22, Katy.Johnston@en21, Ryan.Johnston@en4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
      | search:"n23"                                            | api-dev.metrofoxsecurity.com | "n23"     | null                                        | null        | null        | Andrew.Todd@en23                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | search:"Robert."                                        | api-dev.metrofoxsecurity.com | "Robert." | null                                        | null        | null        | Robert.Abbott@en37, Robert.Holmes@en33                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
      | accreditationSet:["privateInvestigator"]                | api-dev.metrofoxsecurity.com | ""        | listOf("privateInvestigator")               | null        | null        | Andrew.Fleming@en49, Andrew.Mcbride@en38, Andrew.Snyder@en3, Andrew.Todd@en23, Angie.Perez@en29, Annabelle.Elliott@en11, Annabelle.Snyder@en31, Charlotte.Mccarthy@en6, Charlotte.Rivera@en42, Daniel.Edwards@en18, Florence.Mccarthy@en30, James.Hubbard@en13, James.Johnston@en40, Jason.Hunt@en20, Jason.Walton@en28, Katy.Johnston@en21, Matthew.Elliott@en5, Matthew.Hunt@en46, Patrick.O'Brien@en41, Robert.Abbott@en37, Ryan.Johnston@en4, Ryan.O'Brien@en25, Ryan.Walton@en17, William.Holmes@en19, William.Hunt@en2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
      | accreditationSet:["privateInvestigator", "armedGuard"]  | api-dev.metrofoxsecurity.com | ""        | listOf("privateInvestigator", "armedGuard") | null        | null        | Andrew.Fleming@en49, Andrew.Mcbride@en38, Andrew.Snyder@en3, Angie.Perez@en29, Charlotte.Rivera@en42, James.Johnston@en40, Jason.Walton@en28, Matthew.Hunt@en46, Robert.Abbott@en37, Ryan.Johnston@en4, Ryan.O'Brien@en25, William.Holmes@en19, William.Hunt@en2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
      | search:"John", accreditationSet:["privateInvestigator"] | api-dev.metrofoxsecurity.com | "John"    | listOf("privateInvestigator")               | null        | null        | James.Johnston@en40, Katy.Johnston@en21, Ryan.Johnston@en4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
      | all                                                     | api-dev.metrofoxsecurity.com | "John"    | listOf("privateInvestigator")               | "employee"  | "Vacation"  | Katy.Johnston@en21                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
